import { useMemo } from "react";

import { OVERLAY_VIEW_OPTIONS } from "../components/Simulation/Canvas";
import { type UseAppPanelConfigsArgs } from "./appPanelConfigTypes";
import { buildPanelConfigs } from "./panelConfigBuilders";
import { type PanelConfig } from "./worldPanelLayout";

export function useAppPanelConfigs(args: UseAppPanelConfigsArgs): PanelConfig[] {
  const {
    activeAgentPresenceId,
    activeProjection,
    autopilotEvents,
    catalog,
    deferredCoreSimulationTuning,
    deferredPanelsReady,
    flyCameraToAnchor,
    handleUserPresenceInput,
    handleAgentWorkspaceBindingsChange,
    handleAgentWorkspaceContextChange,
    handleAgentWorkspaceSend,
    handleRecord,
    handleSendVoice,
    handleTranscribe,
    handleWorldInteract,
    interactingPersonId,
    isRecording,
    isThinking,
    agentWorkspaceBindings,
    agentWorkspaceContexts,
    projectionStateByElement,
    setActiveAgentPresenceId,
    simulation,
    voiceInputMeta,
    worldInteraction,
  } = args;

  const dedicatedOverlayViews = useMemo(
    () => OVERLAY_VIEW_OPTIONS.filter((option) => option.id !== "omni"),
    [],
  );

  return useMemo(
    () => buildPanelConfigs({
      activeAgentPresenceId,
      activeProjection,
      autopilotEvents,
      catalog,
      deferredCoreSimulationTuning,
      deferredPanelsReady,
      flyCameraToAnchor,
      handleUserPresenceInput,
      handleAgentWorkspaceBindingsChange,
      handleAgentWorkspaceContextChange,
      handleAgentWorkspaceSend,
      handleRecord,
      handleSendVoice,
      handleTranscribe,
      handleWorldInteract,
      interactingPersonId,
      isRecording,
      isThinking,
      agentWorkspaceBindings,
      agentWorkspaceContexts,
      projectionStateByElement,
      setActiveAgentPresenceId,
      simulation,
      voiceInputMeta,
      worldInteraction,
      dedicatedOverlayViews,
    }),
    [
      activeAgentPresenceId,
      activeProjection,
      autopilotEvents,
      catalog,
      deferredCoreSimulationTuning,
      deferredPanelsReady,
      flyCameraToAnchor,
      handleUserPresenceInput,
      handleAgentWorkspaceBindingsChange,
      handleAgentWorkspaceContextChange,
      handleAgentWorkspaceSend,
      handleRecord,
      handleSendVoice,
      handleTranscribe,
      handleWorldInteract,
      interactingPersonId,
      isRecording,
      isThinking,
      agentWorkspaceBindings,
      agentWorkspaceContexts,
      projectionStateByElement,
      setActiveAgentPresenceId,
      simulation,
      voiceInputMeta,
      worldInteraction,
      dedicatedOverlayViews,
    ],
  );
}
